from execution.browser.browser_action import BrowserActions
from core.runtime.async_runtime import AsyncRuntime
from execution.checkout.checkout_verifier import CheckoutVerifier


class CheckoutExecutor:

    def execute(
        self,
        session,
    ):

        print(
            "[CheckoutExecutor] "
            "========== STARTING CHECKOUT =========="
        )

        browser_session = session.browser_session

        if browser_session is None:

            print(
                "[CheckoutExecutor] "
                "Browser session not available."
            )

            return False

        page = browser_session.page

        actions = BrowserActions(
            browser_session,
        )

        print(
            "[CheckoutExecutor] "
            f"Current URL: {page.url}"
        )

        #
        # =====================================================
        # 0. Return to cart
        # =====================================================
        #
        # Monitoring may currently have the same browser session
        # on the PDP because get_pc must be generated by the real
        # browser page.
        #
        # The cart was already prepared before monitoring started.
        #
        if "/cart" not in page.url:

            print(
                "[CheckoutExecutor] "
                "Returning existing session to cart."
            )

            actions.goto(
                "https://shopee.ph/cart"
            )

            if "/cart" not in page.url:

                print(
                    "[CheckoutExecutor] "
                    "Cart page was not reached."
                )

                return False

        print(
            "[CheckoutExecutor] "
            "Cart page confirmed."
        )

        #
        # =====================================================
        # 1. Wait for cart UI
        # =====================================================
        #

        print(
            "[CheckoutExecutor] "
            "Waiting for cart UI..."
        )

        actions.wait_for_timeout(3000)

        #
        # =====================================================
        # 2. Find target cart item
        # =====================================================
        #
        # IMPORTANT:
        #
        # Do NOT rely on the complete product name.
        #
        # Shopee's cart DOM can render/truncate/change the visible
        # product text, so:
        #
        #     text=<full product name>
        #
        # is not a reliable cart-item identity.
        #
        # Instead, inspect cart checkbox containers and match the
        # target using stable identifiers when available.
        #
        # The PurchaseSession gives us:
        #
        #     session.product.item_id
        #
        # and:
        #
        #     session.variation.model_id
        #
        # These are the identities established during PDP parsing
        # and cart preparation.
        #

        print(
            "[CheckoutExecutor] "
            "Searching for target cart item..."
        )

        item_id = str(
            session.product.item_id
        )

        model_id = str(
            session.variation.model_id
        )

        print(
            "[CheckoutExecutor] "
            f"Target Item ID: {item_id}"
        )

        print(
            "[CheckoutExecutor] "
            f"Target Model ID: {model_id}"
        )

        #
        # =====================================================
        # 3. Collect cart checkboxes
        # =====================================================
        #
        # Each cart item has a Shopee checkbox.
        #
        # We use the checkbox as the anchor and inspect its
        # surrounding DOM for the target item identity.
        #

        checkbox_inputs = actions.find_all(
            "input.stardust-checkbox__input"
        )

        checkbox_count = actions.count(
            checkbox_inputs
        )

        print(
            "[CheckoutExecutor] "
            f"Cart checkboxes found: {checkbox_count}"
        )

        if checkbox_count == 0:

            print(
                "[CheckoutExecutor] "
                "No cart item checkboxes found."
            )

            return False

        target_checkbox = None
        target_container = None

        #
        # =====================================================
        # 4. Resolve target cart item
        # =====================================================
        #

        for index in range(checkbox_count):

            checkbox = checkbox_inputs.nth(index)

            print(
                "[CheckoutExecutor] "
                f"Inspecting cart checkbox {index}..."
            )

            current = checkbox

            #
            # Walk upward through the cart DOM.
            #
            # We inspect each parent for item/model identifiers
            # and product text.
            #
            for level in range(1, 9):

                current = actions.parent(
                    current
                )

                if current is None:
                    break

                #
                # ---------------------------------------------
                # Inspect common identity attributes
                # ---------------------------------------------
                #

                identity_values = []

                for attribute_name in (
                    "data-item-id",
                    "data-model-id",
                    "data-product-id",
                    "data-sku-id",
                    "data-id",
                ):

                    value = actions.attribute(
                        current,
                        attribute_name,
                    )

                    if value:
                        identity_values.append(
                            str(value)
                        )

                identity_text = " ".join(
                    identity_values
                )

                #
                # ---------------------------------------------
                # Inspect element text
                # ---------------------------------------------
                #

                container_text = actions.text(
                    current
                )

                if not container_text:
                    container_text = ""

                #
                # ---------------------------------------------
                # Identity matching
                # ---------------------------------------------
                #

                item_match = (
                    item_id in identity_text
                    or item_id in container_text
                )

                model_match = (
                    model_id in identity_text
                    or model_id in container_text
                )

                #
                # The item ID is the primary identity.
                #
                # Model ID is supplemental because Shopee may not
                # expose it directly in the cart DOM.
                #
                if item_match:

                    print(
                        "[CheckoutExecutor] "
                        f"Target item identity found at "
                        f"parent level {level}."
                    )

                    if model_match:

                        print(
                            "[CheckoutExecutor] "
                            "Target item + model identity matched."
                        )

                    else:

                        print(
                            "[CheckoutExecutor] "
                            "Target item matched; "
                            "model ID not exposed at this level."
                        )

                    target_checkbox = checkbox
                    target_container = current

                    break

            if target_checkbox is not None:
                break

        #
        # =====================================================
        # 5. Fallback: product text
        # =====================================================
        #
        # If Shopee doesn't expose item_id in the cart DOM,
        # retain a controlled fallback using the product name.
        #
        # This is intentionally SECONDARY, not the primary lookup.
        #

        if target_checkbox is None:

            print(
                "[CheckoutExecutor] "
                "Stable cart identity not found."
            )

            print(
                "[CheckoutExecutor] "
                "Trying product-name fallback..."
            )

            product_name = (
                session.product.product_name
            )

            product_locator = actions.find_all(
                f"text={product_name}"
            )

            product_count = actions.count(
                product_locator
            )

            print(
                "[CheckoutExecutor] "
                f"Product-name matches: {product_count}"
            )

            if product_count > 0:

                product = actions.first(
                    product_locator
                )

                current = product

                for level in range(1, 9):

                    current = actions.parent(
                        current
                    )

                    if current is None:
                        break

                    checkbox_locator = actions.find_all(
                        "input.stardust-checkbox__input",
                        parent=current,
                    )

                    if actions.count(
                        checkbox_locator
                    ) > 0:

                        target_checkbox = (
                            actions.first(
                                checkbox_locator
                            )
                        )

                        target_container = current

                        print(
                            "[CheckoutExecutor] "
                            "Target cart item resolved "
                            "using product-name fallback."
                        )

                        break

        #
        # =====================================================
        # 6. Target item must exist
        # =====================================================
        #

        if target_checkbox is None:

            print(
                "[CheckoutExecutor] "
                "Target product could not be resolved "
                "inside the cart."
            )

            return False

        print(
            "[CheckoutExecutor] "
            "Target cart item resolved."
        )

        #
        # =====================================================
        # 7. Inspect selection state
        # =====================================================
        #

        aria_checked = actions.attribute(
            target_checkbox,
            "aria-checked",
        )

        print(
            "[CheckoutExecutor] "
            f"aria-checked before: {aria_checked}"
        )

        #
        # Already selected
        #
        if aria_checked == "true":

            print(
                "[CheckoutExecutor] "
                "Target item is already selected."
            )

        else:

            #
            # =================================================
            # 8. Find visible checkbox UI
            # =================================================
            #

            print(
                "[CheckoutExecutor] "
                "Finding visible checkbox UI..."
            )

            checkbox_parent = actions.parent(
                target_checkbox
            )

            checkbox_ui = actions.find_all(
                ".stardust-checkbox__box",
                parent=checkbox_parent,
            )

            checkbox_ui_count = actions.count(
                checkbox_ui
            )

            print(
                "[CheckoutExecutor] "
                f"Checkbox UI boxes found: "
                f"{checkbox_ui_count}"
            )

            if checkbox_ui_count == 0:

                print(
                    "[CheckoutExecutor] "
                    "Visible checkbox UI not found."
                )

                return False

            checkbox_ui = actions.first(
                checkbox_ui
            )

            #
            # =================================================
            # 9. Select target cart item
            # =================================================
            #

            print(
                "[CheckoutExecutor] "
                "Selecting target cart item..."
            )

            actions.click(
                checkbox_ui
            )

            print(
                "[CheckoutExecutor] "
                "Target checkbox clicked."
            )

            #
            # Allow Shopee's reactive UI to update.
            #
            actions.wait_for_timeout(
                500
            )

        #
        # =====================================================
        # 10. Verify selection
        # =====================================================
        #

        aria_checked = actions.attribute(
            target_checkbox,
            "aria-checked",
        )

        print(
            "[CheckoutExecutor] "
            f"aria-checked after: {aria_checked}"
        )

        if aria_checked != "true":

            print(
                "[CheckoutExecutor] "
                "Target item was NOT selected."
            )

            return False

        print(
            "[CheckoutExecutor] "
            "Target item selected successfully."
        )

        #
        # =====================================================
        # 11. Find Check Out button
        # =====================================================
        #

        print(
            "[CheckoutExecutor] "
            "Finding Check Out button..."
        )

        checkout_buttons = actions.find_all(
            "button:has-text('Check Out')"
        )

        checkout_count = actions.count(
            checkout_buttons
        )

        print(
            "[CheckoutExecutor] "
            f"Check Out buttons found: {checkout_count}"
        )

        if checkout_count == 0:

            print(
                "[CheckoutExecutor] "
                "Check Out button not found."
            )

            return False

        checkout_button = actions.first(
            checkout_buttons
        )

        print(
            "[CheckoutExecutor] "
            "Check Out button found."
        )

        #
        # =====================================================
        # 12. Click Check Out
        # =====================================================
        #

        print(
            "[CheckoutExecutor] "
            "Clicking Check Out..."
        )

        actions.click(
            checkout_button
        )

        print(
            "[CheckoutExecutor] "
            "Check Out clicked."
        )

        #
        # Give Shopee time to navigate.
        #
        actions.wait_for_timeout(
            3000
        )

        print(
            "[CheckoutExecutor] "
            f"Current URL after checkout: {page.url}"
        )

        #
        # =====================================================
        # 13. Verify checkout page
        # =====================================================
        #

        if "/checkout" not in page.url:

            print(
                "[CheckoutExecutor] "
                "Checkout page was not reached."
            )

            return False

        print(
            "[CheckoutExecutor] "
            "Checkout page reached."
        )

        #
        # =====================================================
        # 14. Verify Place Order
        # =====================================================
        #
        # IMPORTANT:
        #
        # We intentionally DO NOT click Place Order.
        #
        # The current architecture stops after confirming that
        # the checkout page contains the Place Order control.
        #

        verified = AsyncRuntime.instance().submit(
            CheckoutVerifier().verify_place_order(
                page
            )
        ).result(
            timeout=15
        )

        if not verified:

            print(
                "[CheckoutExecutor] "
                "Place Order button was not detected."
            )

            return False

        print(
            "[CheckoutExecutor] "
            "Place Order button detected."
        )

        print(
            "[CheckoutExecutor] "
            "Checkout verification complete."
        )

        #
        # No Place Order click occurs here.
        #
        return True