"""Phase 4 promotional SKU investigation.

TEST-ONLY. No production application code is modified by this test.
SAFE / observation-only: never clicks Add to Cart, Checkout, or Place Order.

This test validates an observed Shopee behavior:

    promotional URL
        /product/{shop_id}/{item_id}
            -> may resolve/redirect to the canonical PDP URL
        /{product-name}-i.{shop_id}.{item_id}

The test compares both URL forms without performing any cart or checkout
operation. It records the network responses generated during navigation so
we can determine whether /api/v4/pdp/get_pc is emitted by the promotional
URL, by the canonical URL, or by neither.

The application-facing request still uses Storage=256GB. The live ProductInfo
label is resolved dynamically (for example, Capacity) without changing the
production selector.
"""

import argparse
import json
import time
from datetime import datetime, timezone
from pathlib import Path

from core.runtime.async_runtime import AsyncRuntime
from execution.browser.browser_action import BrowserActions
from execution.browser.browser_connector import BrowserConnector
from purchase.parser.shopee_api_parser import ShopeeAPIParser

PROMOTIONAL_URL = "https://shopee.ph/product/1275798143/26342037051"
CANONICAL_URL = "https://shopee.ph/Apple-iPhone-17-Pro-Max-i.1275798143.26342037051"
ITEM_ID = 26342037051
SHOP_ID = 1275798143

REQUESTED_VARIATION = {
    "Color": "Silver",
    "Storage": "256GB",
}

OBSERVE_AFTER_NAVIGATION_SECONDS = 10


def utc_now():
    return datetime.now(timezone.utc).isoformat()


def make_run_dir():
    stamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    path = Path("tests/output") / f"phase4_promo_{stamp}"
    (path / "api").mkdir(parents=True, exist_ok=True)
    return path


def save_json(path, data):
    path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def save_text(path, text):
    path.write_text(text, encoding="utf-8")


def collect_sections(browser_session):
    """Collect PDP section/button information for diagnostics only."""
    actions = BrowserActions(browser_session)
    deadline = time.time() + 8
    last_result = []

    while time.time() < deadline:
        try:
            sections = actions.find_all("section")
            result = []

            for i in range(actions.count(sections)):
                section = sections.nth(i)
                titles = actions.find_all("h2", parent=section)
                if actions.count(titles) == 0:
                    continue

                title = actions.text(titles.first).strip()
                buttons = actions.find_all("button", parent=section)
                values = []
                for j in range(actions.count(buttons)):
                    value = actions.attribute(buttons.nth(j), "aria-label")
                    if value:
                        values.append(value.strip())

                if values:
                    result.append({"title": title, "values": values})

            if result:
                last_result = result
                titles = {item["title"].strip().lower() for item in result}
                if "color" in titles or "capacity" in titles or "storage" in titles:
                    return result
        except Exception:
            pass

        actions.wait_for_timeout(500)

    return last_result


def capture_navigation_get_pc(browser_session, label, target_url, run_dir):
    """Capture all responses generated by one safe PDP navigation.

    The previous test waited specifically for get_pc and failed if that one
    request did not arrive immediately. This version records the whole
    navigation response sequence first, then extracts any get_pc responses.
    That lets us distinguish a dead URL from a changed/redirected request
    sequence without touching production code.
    """
    runtime = AsyncRuntime.instance()
    page = browser_session.page
    captured = []

    async def _capture():
        def on_response(response):
            captured.append(response)

        page.on("response", on_response)
        try:
            await page.goto(
                target_url,
                wait_until="domcontentloaded",
                timeout=30000,
            )
            await page.wait_for_timeout(
                OBSERVE_AFTER_NAVIGATION_SECONDS * 1000
            )

            response_records = []
            get_pc_data = []
            for response in captured:
                response_records.append(
                    {
                        "url": response.url,
                        "status": response.status,
                        "method": response.request.method,
                        "resource_type": response.request.resource_type,
                    }
                )

                if "/api/v4/pdp/get_pc" in response.url:
                    try:
                        get_pc_data.append(
                            {
                                "status": response.status,
                                "url": response.url,
                                "data": await response.json(),
                            }
                        )
                    except Exception as exc:
                        get_pc_data.append(
                            {
                                "status": response.status,
                                "url": response.url,
                                "json_error": repr(exc),
                            }
                        )
        finally:
            try:
                page.remove_listener("response", on_response)
            except Exception:
                pass

        return page.url, response_records, get_pc_data

    try:
        future = runtime.submit(_capture())
        final_url, response_records, get_pc_data = future.result(timeout=50)
    except Exception as exc:
        raise RuntimeError(
            f"Could not inspect {label} navigation: {exc!r}"
        ) from exc

    save_json(
        run_dir / "api" / f"{label}_responses.json",
        response_records,
    )

    get_pc_responses = [item for item in get_pc_data if "data" in item]
    for index, item in enumerate(get_pc_responses, start=1):
        save_json(
            run_dir / "api" / f"{label}_get_pc_{index:02d}.json",
            item["data"],
        )

    print(f"[PHASE4] {label} final URL: {final_url}")
    print(
        f"[PHASE4] {label} captured {len(response_records)} responses; "
        f"get_pc={len(get_pc_responses)}"
    )

    parsed = []
    for item in get_pc_responses:
        parsed.append(
            {
                "status": item["status"],
                "url": item["url"],
                "product": ShopeeAPIParser().parse(item["data"]),
            }
        )

    return final_url, response_records, parsed


def resolve_live_variation_options(product):
    """Resolve the app request against live ProductInfo option keys."""
    product_keys = []
    for variation in product.available_variations:
        for key in variation.options:
            if key not in product_keys:
                product_keys.append(key)

    if not product_keys:
        raise RuntimeError("ProductInfo contained no variation option keys.")

    resolved = {}
    for requested_title, requested_value in REQUESTED_VARIATION.items():
        exact_key = next(
            (
                key
                for key in product_keys
                if key.strip().lower() == requested_title.strip().lower()
            ),
            None,
        )

        if exact_key is not None:
            live_title = exact_key
        else:
            matching_keys = []
            for key in product_keys:
                values = {
                    str(variation.options.get(key, "")).strip().lower()
                    for variation in product.available_variations
                    if key in variation.options
                }
                if requested_value.strip().lower() in values:
                    matching_keys.append(key)

            if len(matching_keys) != 1:
                raise RuntimeError(
                    f"Could not uniquely resolve ProductInfo key for "
                    f"{requested_title} -> {requested_value}: {matching_keys}"
                )
            live_title = matching_keys[0]

        resolved[live_title] = requested_value
        print(
            f"[PHASE4] Application request {requested_title} -> {requested_value} "
            f"resolves to ProductInfo label {live_title} -> {requested_value}"
        )

    return resolved


def find_matching_variations(product, live_request):
    return [
        variation
        for variation in product.available_variations
        if all(
            any(
                key.strip().lower() == requested_key.strip().lower()
                and value.strip().lower() == requested_value.strip().lower()
                for key, value in variation.options.items()
            )
            for requested_key, requested_value in live_request.items()
        )
    ]


def snapshot_page(browser_session, path, label):
    actions = BrowserActions(browser_session)
    try:
        body = actions.find_all("body")
        save_text(path, actions.text(body))
        print(f"[PHASE4] Saved {label}: {path}")
    except Exception as exc:
        print(f"[PHASE4] Could not snapshot {label}: {exc!r}")


def main(args):
    run_dir = make_run_dir()
    manifest = {
        "started_at": utc_now(),
        "promotional_url": PROMOTIONAL_URL,
        "canonical_url": CANONICAL_URL,
        "item_id": ITEM_ID,
        "shop_id": SHOP_ID,
        "requested_variation": REQUESTED_VARIATION,
        "mode": "SAFE / observation only",
        "cart_actions": False,
        "checkout_actions": False,
        "place_order_actions": False,
        "run_dir": str(run_dir),
    }
    save_json(run_dir / "summary.json", manifest)

    owner = object()
    connector = BrowserConnector()
    browser_session = None

    try:
        print("=" * 72)
        print("PHASE 4 — PROMOTIONAL SKU INVESTIGATION")
        print("=" * 72)
        print(f"Promotional URL: {PROMOTIONAL_URL}")
        print(f"Canonical URL:   {CANONICAL_URL}")
        print(f"Item: {ITEM_ID} | Shop: {SHOP_ID}")
        print(f"Requested SKU: {REQUESTED_VARIATION}")
        print("Mode: SAFE / observation only")
        print("=" * 72)

        connector.connect()
        browser_session = connector.open_session(owner, PROMOTIONAL_URL)
        print(f"[PHASE4] Initial URL: {browser_session.page.url}")
        manifest["initial_connector_url"] = browser_session.page.url

        sections = collect_sections(browser_session)
        manifest["initial_live_sections"] = sections
        if sections:
            print("[PHASE4] Initial PDP sections observed:")
            for section in sections:
                print(f"[PHASE4]   {section['title']}: {section['values']}")
        else:
            print("[PHASE4] PDP section/button DOM not observed.")

        # A: Observe the promotional URL directly.
        promo_final_url, promo_responses, promo_get_pc = capture_navigation_get_pc(
            browser_session,
            "promotional",
            PROMOTIONAL_URL,
            run_dir,
        )
        manifest["promotional_final_url"] = promo_final_url
        manifest["promotional_response_count"] = len(promo_responses)
        manifest["promotional_get_pc_count"] = len(promo_get_pc)
        manifest["promotional_get_pc_urls"] = [item["url"] for item in promo_get_pc]

        if promo_get_pc:
            promo_product = promo_get_pc[-1]["product"]
            print(
                f"[PHASE4] Promotional URL produced ProductInfo: "
                f"{promo_product.product_name}"
            )
        else:
            promo_product = None
            print("[PHASE4] Promotional URL produced NO get_pc response.")

        # B: Observe the canonical URL as a control. This URL was observed
        # manually after opening the promotional listing from the cart.
        canonical_final_url, canonical_responses, canonical_get_pc = (
            capture_navigation_get_pc(
                browser_session,
                "canonical",
                CANONICAL_URL,
                run_dir,
            )
        )
        manifest["canonical_final_url"] = canonical_final_url
        manifest["canonical_response_count"] = len(canonical_responses)
        manifest["canonical_get_pc_count"] = len(canonical_get_pc)
        manifest["canonical_get_pc_urls"] = [item["url"] for item in canonical_get_pc]

        if canonical_get_pc:
            canonical_product = canonical_get_pc[-1]["product"]
            print(
                f"[PHASE4] Canonical URL produced ProductInfo: "
                f"{canonical_product.product_name}"
            )
        else:
            canonical_product = None
            print("[PHASE4] Canonical URL produced NO get_pc response.")

        # Use whichever live ProductInfo is available for the SKU mapping
        # validation. Prefer promotional data when it exists.
        product = promo_product or canonical_product
        if product is None:
            raise RuntimeError(
                "Neither promotional nor canonical PDP navigation produced "
                "a parseable get_pc response. Inspect api/*_responses.json "
                "for the captured network evidence."
            )

        if product.item_id != ITEM_ID or product.shop_id != SHOP_ID:
            raise RuntimeError(
                "Selected ProductInfo does not match the expected listing: "
                f"expected item/shop {ITEM_ID}/{SHOP_ID}, got "
                f"{product.item_id}/{product.shop_id}"
            )

        manifest["product"] = {
            "item_id": product.item_id,
            "shop_id": product.shop_id,
            "product_name": product.product_name,
            "url": product.product_url,
        }

        product_option_keys = sorted(
            {
                key
                for variation in product.available_variations
                for key in variation.options
            }
        )
        manifest["product_option_keys"] = product_option_keys
        print(f"[PHASE4] ProductInfo option keys: {product_option_keys}")

        live_request = resolve_live_variation_options(product)
        manifest["live_test_request"] = live_request

        matching = find_matching_variations(product, live_request)
        if len(matching) != 1:
            raise RuntimeError(
                "Live SKU resolution was not unique: "
                + json.dumps(
                    [
                        {
                            "model_id": variation.model_id,
                            "name": variation.name,
                            "options": variation.options,
                        }
                        for variation in matching
                    ],
                    ensure_ascii=False,
                )
            )

        variation = matching[0]
        manifest["variation"] = {
            "model_id": variation.model_id,
            "name": variation.name,
            "options": variation.options,
            "price": variation.price,
            "price_before_discount": variation.price_before_discount,
            "has_stock": variation.has_stock,
            "tier_index": variation.tier_index,
        }

        print(
            f"[PHASE4] Exact requested live SKU: "
            f"{variation.name} | model={variation.model_id}"
        )
        print(f"[PHASE4] Live ProductInfo options: {variation.options}")

        # Compare whether the exact resolved model is present in both URL
        # forms' ProductInfo when both produced get_pc.
        manifest["exact_model_presence"] = {
            "model_id": variation.model_id,
            "promotional": any(
                any(
                    item.model_id == variation.model_id
                    for item in result["product"].available_variations
                )
                for result in promo_get_pc
            ),
            "canonical": any(
                any(
                    item.model_id == variation.model_id
                    for item in result["product"].available_variations
                )
                for result in canonical_get_pc
            ),
        }

        manifest["diagnosis"] = {
            "promotional_get_pc": bool(promo_get_pc),
            "canonical_get_pc": bool(canonical_get_pc),
            "promotional_resolved_to_canonical": (
                promo_final_url != PROMOTIONAL_URL
                and ITEM_ID.__str__() in promo_final_url
                and SHOP_ID.__str__() in promo_final_url
            ),
        }

        snapshot_page(
            browser_session,
            run_dir / "final_page.txt",
            "final page",
        )
        manifest["finished_at"] = utc_now()
        save_json(run_dir / "summary.json", manifest)

        print("=" * 72)
        print("PHASE 4 RESULT")
        print("=" * 72)
        print(
            "Promotional get_pc:   ",
            "PASS" if promo_get_pc else "NOT OBSERVED",
        )
        print(
            "Canonical get_pc:     ",
            "PASS" if canonical_get_pc else "NOT OBSERVED",
        )
        print(f"Promotional final URL: {promo_final_url}")
        print(f"Canonical final URL:   {canonical_final_url}")
        print(f"Exact SKU resolved:    PASS | model {variation.model_id}")
        print(f"Evidence directory:    {run_dir}")
        print("Add to Cart clicked:    NO")
        print("Checkout clicked:       NO")
        print("Place Order clicked:    NO")
        print("=" * 72)
        return 0

    except Exception as exc:
        manifest["finished_at"] = utc_now()
        manifest["error"] = str(exc)
        save_json(run_dir / "summary.json", manifest)
        print(f"[PHASE4] FAILED: {exc!r}")
        return 1

    finally:
        try:
            if browser_session is not None:
                connector.close_session(owner)
        except Exception as exc:
            print(f"[PHASE4] Cleanup warning: {exc!r}")


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--monitor-seconds", type=int, default=120)
    parser.add_argument("--poll-interval", type=int, default=5)
    return parser.parse_args()


if __name__ == "__main__":
    raise SystemExit(main(parse_args()))
