"""
Read-only inspection of Shopee's My Purchase /user/purchase/ page.

Purpose
-------
This test is deliberately isolated from the production purchase pipeline. It
connects to the existing Chrome instance through the project's BrowserEngine,
opens a separate tab, visits /user/purchase/, and inspects:

* visible order-list text and useful DOM attributes
* order-related links/buttons
* network requests made by the purchase page
* JSON response structures from order/purchase-related APIs
* candidate fields for Order ID, order status, payment deadline, totals,
  product/item/model identifiers, and seller information

It DOES NOT:
* place an order
* click Pay Now / Place Order / Cancel
* change payment state
* modify the existing application code or services
* call any Shopee write endpoint intentionally

The goal is discovery only. The output should tell us which page/API source
is authoritative for the future Discord "Order created — payment required"
notification.

Run from the repository root with the project's virtual environment:

    python3 tests/test_purchase_order_inspector.py

Chrome must already be running with remote debugging on localhost:9222 and
logged into the Shopee account whose purchase page is being inspected.
"""

from __future__ import annotations

import asyncio
import json
import re
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

from core.runtime.async_runtime import AsyncRuntime
from execution.browser.browser_engine import BrowserEngine


PURCHASE_URL = "https://shopee.ph/user/purchase/"

# Only GET-like read endpoints are interesting for this inspection. The test
# never calls page.request directly; it only observes requests generated by
# the page itself.
API_MARKERS = (
    "/api/",
    "/graphql",
)
ORDER_MARKERS = (
    "order",
    "purchase",
    "unpaid",
    "pending",
    "checkout",
    "payment",
    "logistics",
    "shipment",
)

CANDIDATE_KEY_MARKERS = (
    "order",
    "ordersn",
    "order_sn",
    "orderid",
    "order_id",
    "item",
    "model",
    "product",
    "shop",
    "seller",
    "amount",
    "total",
    "price",
    "payment",
    "deadline",
    "expire",
    "status",
    "create",
    "time",
    "voucher",
    "shipping",
)

# Keys whose values can contain account/security material are never printed.
SENSITIVE_KEY_MARKERS = (
    "token",
    "cookie",
    "authorization",
    "access_key",
    "secret",
    "signature",
    "nonce",
    "client_id",
    "redirect",
    "phone",
    "email",
    "address",
)

MAX_BODY_TEXT = 12000
MAX_JSON_DEPTH = 6
MAX_JSON_ITEMS = 250


def safe_url(url: str) -> str:
    """Keep query parameter names while replacing their values."""
    parsed = urlsplit(url)
    pairs = []
    for key, _ in parse_qsl(parsed.query, keep_blank_values=True):
        pairs.append((key, "<redacted>"))

    query = urlencode(pairs)
    return urlunsplit((parsed.scheme, parsed.netloc, parsed.path, query, ""))


def normalize(value: Any) -> str:
    return " ".join(str(value).split()).strip()


def key_is_sensitive(key: str) -> bool:
    lowered = key.lower()
    return any(marker in lowered for marker in SENSITIVE_KEY_MARKERS)


def key_is_candidate(key: str) -> bool:
    lowered = key.lower()
    return any(marker in lowered for marker in CANDIDATE_KEY_MARKERS)


def compact_value(value: Any) -> Any:
    """Make a JSON value safe and compact enough for terminal output."""
    if isinstance(value, str):
        text = normalize(value)
        return text[:300] + ("..." if len(text) > 300 else "")
    if isinstance(value, (int, float, bool)) or value is None:
        return value
    if isinstance(value, list):
        return [compact_value(item) for item in value[:20]]
    if isinstance(value, dict):
        result = {}
        for key, item in list(value.items())[:80]:
            if key_is_sensitive(str(key)):
                continue
            result[str(key)] = compact_value(item)
        return result
    return normalize(value)[:300]


def collect_candidate_fields(
    value: Any,
    path: str = "$",
    depth: int = 0,
) -> list[tuple[str, Any]]:
    """Recursively find useful order/purchase fields without dumping payloads."""
    if depth > MAX_JSON_DEPTH:
        return []

    found: list[tuple[str, Any]] = []

    if isinstance(value, dict):
        for key, child in list(value.items())[:MAX_JSON_ITEMS]:
            key_text = str(key)
            child_path = f"{path}.{key_text}"

            if key_is_candidate(key_text) and not key_is_sensitive(key_text):
                found.append((child_path, compact_value(child)))

            found.extend(
                collect_candidate_fields(
                    child,
                    child_path,
                    depth + 1,
                )
            )

    elif isinstance(value, list):
        for index, child in enumerate(value[:MAX_JSON_ITEMS]):
            found.extend(
                collect_candidate_fields(
                    child,
                    f"{path}[{index}]",
                    depth + 1,
                )
            )

    return found


def looks_like_order_api(url: str) -> bool:
    lowered = url.lower()
    return any(marker in lowered for marker in ORDER_MARKERS)


def is_api_request(url: str) -> bool:
    lowered = url.lower()
    return any(marker in lowered for marker in API_MARKERS)


def print_header(title: str) -> None:
    print("\n" + "=" * 78)
    print(title)
    print("=" * 78)


async def inspect_purchase_page(page: Any) -> None:
    observed_responses: list[dict[str, Any]] = []

    async def on_response(response: Any) -> None:
        url = response.url
        if not is_api_request(url) or not looks_like_order_api(url):
            return

        request = response.request
        method = getattr(request, "method", "GET")
        if method.upper() not in {"GET", "POST"}:
            return

        record: dict[str, Any] = {
            "method": method.upper(),
            "status": response.status,
            "url": url,
            "safe_url": safe_url(url),
            "content_type": "",
            "json": None,
            "json_error": None,
        }

        try:
            record["content_type"] = response.headers.get("content-type", "")
        except Exception:
            pass

        content_type = str(record["content_type"]).lower()
        if "json" not in content_type:
            observed_responses.append(record)
            return

        try:
            payload = await response.json()
            record["json"] = payload
        except Exception as exc:
            record["json_error"] = str(exc)

        observed_responses.append(record)

    page.on("response", on_response)

    try:
        print_header("SHOPEE PURCHASE PAGE INSPECTION")
        print(f"Target URL: {PURCHASE_URL}")
        print("Mode      : READ-ONLY / DISCOVERY")
        print("Actions   : NO purchase/payment/cancellation actions")

        print("\n[NAVIGATION] Opening /user/purchase/ in a separate browser tab...")
        await page.goto(
            PURCHASE_URL,
            wait_until="domcontentloaded",
            timeout=30000,
        )

        try:
            await page.wait_for_load_state("networkidle", timeout=10000)
        except Exception:
            # Shopee can keep background requests open indefinitely. DOM
            # inspection remains useful after domcontentloaded.
            pass

        await asyncio.sleep(3)

        print_header("PAGE STATE")
        print(f"URL   : {safe_url(page.url)}")
        try:
            print(f"Title : {normalize(await page.title())}")
        except Exception:
            print("Title : <unavailable>")

        body_text = ""
        try:
            body_text = await page.locator("body").inner_text(timeout=5000)
            body_text = normalize(body_text)
        except Exception as exc:
            print(f"Body  : <unavailable: {exc}>")

        if body_text:
            print("\nVISIBLE PAGE TEXT")
            print("-" * 78)
            print(body_text[:MAX_BODY_TEXT])
            if len(body_text) > MAX_BODY_TEXT:
                print("... <body text truncated>")

        print_header("ORDER-RELATED DOM ELEMENTS")

        # We inspect, but deliberately do not click, buttons or links.
        elements = page.locator(
            "a, button, [role='button'], [data-testid], [class]"
        )
        count = min(await elements.count(), 500)
        print(f"Elements sampled: {count}")

        interesting_count = 0
        seen_lines: set[str] = set()

        for index in range(count):
            element = elements.nth(index)
            try:
                text = normalize(await element.inner_text(timeout=300))
            except Exception:
                text = ""

            try:
                href = await element.get_attribute("href")
            except Exception:
                href = None

            try:
                testid = await element.get_attribute("data-testid")
            except Exception:
                testid = None

            descriptor = " ".join(
                part
                for part in (text, href or "", testid or "")
                if part
            )

            lowered = descriptor.lower()
            if not any(
                marker in lowered
                for marker in (
                    "to pay",
                    "pay now",
                    "order",
                    "purchase",
                    "pending",
                    "cancel",
                    "shipment",
                    "tracking",
                    "seller",
                )
            ):
                continue

            safe_href = safe_url(href) if href and href.startswith("http") else href
            line = f"#{index}: text={text[:180]!r} href={safe_href!r} data-testid={testid!r}"
            if line in seen_lines:
                continue
            seen_lines.add(line)
            print(line)
            interesting_count += 1

            if interesting_count >= 150:
                print("... <DOM sample limit reached>")
                break

        if interesting_count == 0:
            print("No order-related DOM elements matched the inspection markers.")

        # Capture links separately because order detail links can be useful
        # even when their visible text is abbreviated.
        print_header("PURCHASE / ORDER LINKS")
        links = page.locator("a[href]")
        link_count = await links.count()
        found_links = 0

        for index in range(min(link_count, 500)):
            link = links.nth(index)
            try:
                href = await link.get_attribute("href")
                text = normalize(await link.inner_text(timeout=300))
            except Exception:
                continue

            if not href:
                continue

            lowered = href.lower()
            if not any(marker in lowered for marker in ("order", "purchase", "user/purchase")):
                continue

            print(
                f"LINK #{index}: text={text[:180]!r} href={safe_url(href) if href.startswith('http') else href!r}"
            )
            found_links += 1

        if found_links == 0:
            print("No explicit order/purchase links found in the current DOM.")

        print_header("OBSERVED ORDER/PURCHASE API RESPONSES")
        print(f"Responses observed: {len(observed_responses)}")

        if not observed_responses:
            print(
                "No matching order/purchase API response was observed. "
                "This can mean the page rendered from cached state, uses a "
                "different endpoint name, or requires another read-only tab action."
            )

        for index, record in enumerate(observed_responses, start=1):
            print(f"\nRESPONSE #{index}")
            print("-" * 78)
            print(f"Method       : {record['method']}")
            print(f"Status       : {record['status']}")
            print(f"Content-Type : {record['content_type']}")
            print(f"URL          : {record['safe_url']}")

            payload = record.get("json")
            if payload is None:
                if record.get("json_error"):
                    print(f"JSON         : <unavailable: {record['json_error']}>")
                else:
                    print("JSON         : <not JSON>")
                continue

            print(f"Top-level type: {type(payload).__name__}")
            if isinstance(payload, dict):
                print(f"Top-level keys: {list(payload.keys())[:100]}")
            elif isinstance(payload, list):
                print(f"Top-level list length: {len(payload)}")

            candidates = collect_candidate_fields(payload)
            if not candidates:
                print("Candidate fields: none found")
                continue

            print("Candidate fields:")
            printed = 0
            seen_candidates: set[str] = set()
            for path, value in candidates:
                line = f"  {path} = {json.dumps(value, ensure_ascii=False)}"
                if line in seen_candidates:
                    continue
                seen_candidates.add(line)
                print(line[:1200])
                printed += 1
                if printed >= 250:
                    print("  ... <candidate field limit reached>")
                    break

        print_header("ORDER-ID / PAYMENT-DEADLINE DISCOVERY SUMMARY")

        order_id_candidates: list[tuple[str, Any, str]] = []
        deadline_candidates: list[tuple[str, Any, str]] = []

        for record in observed_responses:
            payload = record.get("json")
            if payload is None:
                continue

            for path, value in collect_candidate_fields(payload):
                lowered = path.lower()
                if any(
                    marker in lowered
                    for marker in ("order_sn", "orderid", "order_id", "orderno", "order_no")
                ):
                    order_id_candidates.append((path, value, record["safe_url"]))

                if any(
                    marker in lowered
                    for marker in ("deadline", "expire", "payment_time_limit", "pay_by")
                ):
                    deadline_candidates.append((path, value, record["safe_url"]))

        print("Potential Order ID fields:")
        if order_id_candidates:
            for path, value, source in order_id_candidates[:100]:
                print(f"  {path} = {json.dumps(value, ensure_ascii=False)}")
                print(f"    source: {source}")
        else:
            print("  NONE found in observed API payloads.")

        print("\nPotential payment-deadline fields:")
        if deadline_candidates:
            for path, value, source in deadline_candidates[:100]:
                print(f"  {path} = {json.dumps(value, ensure_ascii=False)}")
                print(f"    source: {source}")
        else:
            print("  NONE found in observed API payloads.")

        print_header("INSPECTION COMPLETE")
        print(
            "No purchase, payment, cancellation, or write action was intentionally "
            "performed by this test. Use the output above to identify the authoritative "
            "Order ID and payment-pending fields before implementing Discord notification."
        )

    finally:
        try:
            page.remove_listener("response", on_response)
        except Exception:
            pass


def main() -> None:
    runtime = AsyncRuntime.instance()
    engine = BrowserEngine.instance()
    owner = object()

    future = runtime.submit(
        engine.open_session(
            owner,
            "about:blank",
        )
    )
    session = future.result(timeout=30)
    page = session.page

    try:
        runtime.submit(inspect_purchase_page(page)).result(timeout=90)
    finally:
        runtime.submit(engine.close_session(owner)).result(timeout=15)


if __name__ == "__main__":
    main()
