"""
Isolated diagnostic for Shopee campaign/product URLs.

This test does NOT modify production monitoring, cart, checkout, or IME code.
It opens the supplied URL in the existing BrowserEngine and inspects the
network responses generated by Shopee so we can determine where campaign,
flash-sale, event, and SKU pricing information is exposed.

Usage:
    python3 tests/test_shopee_campaign_inspection.py
    python3 tests/test_shopee_campaign_inspection.py --dump /tmp/shopee_campaign.json
"""

import argparse
import asyncio
import json
from pathlib import Path
from threading import Event

from execution.browser.browser_connector import BrowserConnector


URL = "https://shopee.ph/product/1275798143/26342037051"


class CampaignInspector:
    """Collects read-only network evidence for one Shopee URL."""

    def __init__(self):
        self.browser = BrowserConnector()
        self.loaded = Event()
        self.responses = []
        self.get_pc_payloads = []
        self.session = None

    def run(self, url, timeout=20):
        self.browser.connect()
        self.browser.engine.register_response_callback(
            self,
            self.on_response,
        )

        try:
            self.session = self.browser.open_session(
                self,
                url,
            )

            if not self.loaded.wait(timeout=timeout):
                raise TimeoutError(
                    "Timed out waiting for Shopee get_pc response."
                )

            # Allow closely related campaign/promotion requests generated by
            # the initial page load to arrive before we close the tab.
            self.browser.runtime.submit(
                asyncio.sleep(2)
            ).result(timeout=5)

            final_url = self.session.url
        finally:
            self.browser.close_session(self)
            self.session = None
            self.browser.engine.unregister_response_callback(self)

        return final_url

    async def on_response(self, response):
        url = response.url

        record = {
            "url": url,
            "status": response.status,
            "content_type": response.headers.get("content-type", ""),
        }

        self.responses.append(record)

        if "/api/v4/pdp/get_pc" not in url:
            return

        print("[CampaignInspector] get_pc response detected.")

        try:
            payload = await response.json()
        except Exception as exc:
            print(f"[CampaignInspector] Failed to decode get_pc JSON: {exc}")
            self.loaded.set()
            return

        self.get_pc_payloads.append(payload)
        self.loaded.set()

    def build_report(self, source_url, final_url):
        payload = self.get_pc_payloads[-1] if self.get_pc_payloads else None

        report = {
            "source_url": source_url,
            "final_url": final_url,
            "get_pc_response_count": len(self.get_pc_payloads),
            "matching_responses": self._interesting_responses(),
            "product_identity": self._product_identity(payload),
            "models": self._models(payload),
            "promotion_fields": self._matching_paths(
                payload,
                ("promotion", "promo", "event", "campaign", "flash"),
            ),
            "price_fields": self._matching_paths(
                payload,
                ("price", "discount", "original"),
            ),
            "raw_get_pc": payload,
        }

        return report

    def _interesting_responses(self):
        keywords = (
            "promotion",
            "promo",
            "campaign",
            "flash",
            "event",
            "discount",
            "voucher",
            "mart",
        )

        return [
            item
            for item in self.responses
            if any(keyword in item["url"].lower() for keyword in keywords)
        ]

    @staticmethod
    def _product_identity(payload):
        if not isinstance(payload, dict):
            return {}

        item = payload.get("data", {}).get("item", {})

        if not isinstance(item, dict):
            return {}

        return {
            "item_id": item.get("item_id"),
            "shop_id": item.get("shop_id"),
            "title": item.get("title"),
            "share_link": item.get("share_link"),
            "currency": item.get("currency"),
            "shop_name": item.get("shop_name"),
        }

    @staticmethod
    def _models(payload):
        if not isinstance(payload, dict):
            return []

        item = payload.get("data", {}).get("item", {})
        models = item.get("models", []) if isinstance(item, dict) else []
        tier_variations = (
            item.get("tier_variations", [])
            if isinstance(item, dict)
            else []
        )

        result = []

        for model in models:
            if not isinstance(model, dict):
                continue

            extinfo = model.get("extinfo", {})
            tier_index = extinfo.get("tier_index", [])
            options = []

            for index, tier in zip(tier_index, tier_variations):
                values = tier.get("options", [])
                if isinstance(index, int) and 0 <= index < len(values):
                    options.append(
                        {
                            "tier": tier.get("name"),
                            "option": values[index],
                        }
                    )

            result.append(
                {
                    "model_id": model.get("model_id"),
                    "price": model.get("price"),
                    "price_before_discount": model.get(
                        "price_before_discount"
                    ),
                    "has_stock": model.get("has_stock"),
                    "tier_index": tier_index,
                    "selected_options": options,
                    "raw_extinfo": extinfo,
                }
            )

        return result

    @classmethod
    def _matching_paths(cls, payload, keywords):
        matches = []

        def walk(value, path):
            if isinstance(value, dict):
                for key, child in value.items():
                    child_path = f"{path}.{key}" if path else str(key)
                    key_lower = str(key).lower()

                    if any(keyword in key_lower for keyword in keywords):
                        matches.append(
                            {
                                "path": child_path,
                                "value": child,
                            }
                        )

                    walk(child, child_path)

            elif isinstance(value, list):
                for index, child in enumerate(value):
                    walk(child, f"{path}[{index}]")

        walk(payload, "")
        return matches


def print_report(report):
    print()
    print("=" * 70)
    print("SHOPEE CAMPAIGN / PRODUCT URL INSPECTION")
    print("=" * 70)
    print("Source URL :", report["source_url"])
    print("Final URL  :", report["final_url"])
    print("get_pc     :", report["get_pc_response_count"], "response(s)")

    print()
    print("---------- PRODUCT IDENTITY ----------")
    for key, value in report["product_identity"].items():
        print(f"{key:15}: {value}")

    print()
    print("---------- MODELS / SKU PRICING ----------")
    for model in report["models"]:
        print("------------------------------------------")
        print("Model ID              :", model["model_id"])
        print("Raw price             :", model["price"])
        print("Raw price before disc :", model["price_before_discount"])
        print("Has stock             :", model["has_stock"])
        print("Selected options      :", model["selected_options"])
        print("Extinfo keys          :", sorted(model["raw_extinfo"].keys()))

    print()
    print("---------- PROMOTION / CAMPAIGN FIELDS ----------")
    if not report["promotion_fields"]:
        print("No matching promotion/campaign/event fields found.")
    else:
        for item in report["promotion_fields"]:
            print("PATH :", item["path"])
            print("VALUE:", repr(item["value"]))
            print()

    print()
    print("---------- PRICE / DISCOUNT FIELDS ----------")
    if not report["price_fields"]:
        print("No matching price/discount fields found.")
    else:
        for item in report["price_fields"]:
            print("PATH :", item["path"])
            print("VALUE:", repr(item["value"]))
            print()

    print()
    print("---------- RELATED NETWORK RESPONSES ----------")
    if not report["matching_responses"]:
        print("No campaign/promotion-related response URLs detected.")
    else:
        for item in report["matching_responses"]:
            print(f"{item['status']} {item['url']}")

    print()
    print("Full raw get_pc JSON is included in the optional dump file.")
    print("=" * 70)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--url",
        default=URL,
        help="Shopee URL to inspect.",
    )
    parser.add_argument(
        "--dump",
        help="Optional path for the complete JSON inspection report.",
    )
    args = parser.parse_args()

    inspector = CampaignInspector()
    final_url = inspector.run(args.url)
    report = inspector.build_report(args.url, final_url)
    print_report(report)

    if args.dump:
        path = Path(args.dump).expanduser()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(report, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        print(f"[CampaignInspector] Full report written to: {path}")


if __name__ == "__main__":
    main()
