"""
Read-only inspection of Shopee's My Purchase /user/purchase/ page.

This test is deliberately isolated from the production purchase pipeline.
It opens /user/purchase/ in a separate browser tab, observes the page's own
network traffic, and extracts a structured representation of the checkout/order
that matches a known monitored item.

IMPORTANT
---------
This file is TEST-ONLY. It must not place, pay, cancel, modify, or otherwise
write an order. It does not call Shopee APIs directly; it only observes GET/
POST responses generated by the page itself.

The matcher is designed for the state immediately after Place Order succeeds:

    monitored item
        -> /user/purchase/
        -> get_all_order_and_checkout_list response
        -> checkout_list_detail
        -> info_card.order_list_cards[*]
        -> actual order_id

The checkout ID and Order ID are intentionally treated as different values.
For the successful test order discovered previously:

    checkout_id = 241792195239038
    order_id    = 241792195231162

Run from the repository root:

    python3 tests/test_purchase_order_inspector.py

Optional target selectors can be supplied when the monitored item is not the
known test item:

    --product-name "Exact or partial product name"
    --item-id 52201950487
    --model-id 400189597306
    --shop-id 1680631055
    --checkout-id 241792195239038
    --wait-seconds 5

Selectors may be combined. A candidate must satisfy every selector supplied.
If no selectors are supplied, the known successful test item's fingerprint is
used so that the test can reproduce the discovery shown in the project work.

Chrome must already be running with remote debugging on localhost:9222 and
logged into the Shopee account whose purchase page is being inspected.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from core.runtime.async_runtime import AsyncRuntime
from execution.browser.browser_engine import BrowserEngine


PURCHASE_URL = "https://shopee.ph/user/purchase/"

# Fingerprint of the real successful monitored item used during discovery.
# CLI selectors override these defaults, so this remains useful for future
# monitored products without requiring production-code changes.
DEFAULT_PRODUCT_NAME = (
    "Custom Make Single Sleeved Pet Mechanical Keyboard Coiled USB To Type C "
    "Mini Micro Spiral Cable Colorful Gx12 Aviation Socket"
)
DEFAULT_ITEM_ID = 52201950487
DEFAULT_MODEL_ID = 400189597306
DEFAULT_SHOP_ID = 1680631055

ORDER_LIST_ENDPOINT = "/api/v4/order/get_all_order_and_checkout_list"
ORDER_MARKERS = (
    "order",
    "purchase",
    "checkout",
    "payment",
    "unpaid",
    "pending",
)
SENSITIVE_KEY_MARKERS = (
    "token",
    "cookie",
    "authorization",
    "access_key",
    "secret",
    "signature",
    "nonce",
    "client_id",
    "redirect",
    "phone",
    "email",
    "address",
)
MAX_BODY_TEXT = 12000
MAX_JSON_DEPTH = 12
MAX_JSON_ITEMS = 500


@dataclass(frozen=True)
class Target:
    product_name: str | None = None
    item_id: int | None = None
    model_id: int | None = None
    shop_id: int | None = None
    checkout_id: int | None = None


@dataclass
class OrderMatch:
    source_url: str
    container_index: int
    container_type: str
    checkout_id: int | None = None
    order_id: int | None = None
    status: str | None = None
    status_label: str | None = None
    payment_method: str | None = None
    payment_deadline: datetime | None = None
    payment_deadline_raw: int | float | str | None = None
    shop_id: int | None = None
    shop_name: str | None = None
    seller_username: str | None = None
    item_id: int | None = None
    model_id: int | None = None
    product_name: str | None = None
    variation: str | None = None
    quantity: int | None = None
    item_price: int | None = None
    original_price: int | None = None
    order_price: int | None = None
    subtotal: int | None = None
    final_total: int | None = None
    checkout_status: int | None = None
    raw_card: dict[str, Any] = field(default_factory=dict)


def safe_url(url: str) -> str:
    parsed = urlsplit(url)
    pairs = [(key, "<redacted>") for key, _ in parse_qsl(parsed.query, keep_blank_values=True)]
    return urlunsplit((parsed.scheme, parsed.netloc, parsed.path, urlencode(pairs), ""))


def normalize(value: Any) -> str:
    return " ".join(str(value).split()).strip()


def key_is_sensitive(key: str) -> bool:
    lowered = key.lower()
    return any(marker in lowered for marker in SENSITIVE_KEY_MARKERS)


def int_value(value: Any) -> int | None:
    if isinstance(value, bool) or value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def money_php(value: int | None) -> str:
    if value is None:
        return "<not found>"
    return f"₱{value / 100000:,.2f}"


def parse_timestamp(value: Any) -> datetime | None:
    """Shopee's type-8/type-7 attributes are Unix seconds."""
    number = int_value(value)
    if number is None or number <= 0:
        return None
    try:
        return datetime.fromtimestamp(number, tz=timezone.utc).astimezone()
    except (OverflowError, OSError, ValueError):
        return None


def text_field(obj: Any, *keys: str) -> str | None:
    if not isinstance(obj, dict):
        return None
    for key in keys:
        value = obj.get(key)
        if value is not None and normalize(value):
            return normalize(value)
    return None


def nested_first_item(card: dict[str, Any]) -> dict[str, Any] | None:
    product_info = card.get("product_info")
    if not isinstance(product_info, dict):
        return None
    groups = product_info.get("item_groups")
    if not isinstance(groups, list):
        return None
    for group in groups:
        if not isinstance(group, dict):
            continue
        items = group.get("items")
        if not isinstance(items, list):
            continue
        for item in items:
            if isinstance(item, dict):
                return item
    return None


def payment_info(status: dict[str, Any]) -> tuple[str | None, int | float | str | None, datetime | None]:
    if not isinstance(status, dict):
        return None, None, None

    # The observed payload uses a translation key such as
    # order_status_text_pay_shopee_kredit_by. Keep the raw key because it is
    # the strongest available indication of the payment method without
    # guessing a localized label.
    header = status.get("header_text")
    payment_method = None
    raw_deadline: int | float | str | None = None

    if isinstance(header, dict):
        text_key = normalize(header.get("text", ""))
        if text_key:
            if "shopee_kredit" in text_key.lower() or "spaylater" in text_key.lower():
                payment_method = "SPayLater"
            else:
                payment_method = text_key

        attributes = header.get("attributes")
        if isinstance(attributes, list):
            for attribute in attributes:
                if not isinstance(attribute, dict):
                    continue
                name = normalize(attribute.get("name", "")).lower()
                if name in {"payby_date", "pay_by_date", "payment_deadline", "expire_time"}:
                    raw_deadline = attribute.get("value")
                    break

    deadline = parse_timestamp(raw_deadline)
    return payment_method, raw_deadline, deadline


def iter_order_containers(payload: Any) -> list[tuple[int, str, dict[str, Any]]]:
    """Return checkout/order entries from the authoritative list response."""
    if not isinstance(payload, dict):
        return []

    new_data = payload.get("new_data")
    if not isinstance(new_data, dict):
        return []

    entries = new_data.get("order_or_checkout_data")
    if not isinstance(entries, list):
        return []

    result: list[tuple[int, str, dict[str, Any]]] = []
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            continue
        if isinstance(entry.get("checkout_list_detail"), dict):
            result.append((index, "checkout_list_detail", entry["checkout_list_detail"]))
        elif isinstance(entry.get("order_list_detail"), dict):
            result.append((index, "order_list_detail", entry["order_list_detail"]))
    return result


def build_match(
    payload: Any,
    source_url: str,
    index: int,
    container_type: str,
    container: dict[str, Any],
) -> list[OrderMatch]:
    info = container.get("info_card")
    if not isinstance(info, dict):
        return []

    checkout_id = int_value(info.get("checkout_id"))
    checkout_status = int_value(info.get("checkout_status"))

    status = container.get("status")
    status_label = None
    status_text = None
    if isinstance(status, dict):
        label = status.get("list_view_status_label")
        if isinstance(label, dict):
            status_label = text_field(label, "text")
        header = status.get("header_text")
        if isinstance(header, dict):
            status_text = text_field(header, "text")

    payment_method, raw_deadline, deadline = payment_info(status if isinstance(status, dict) else {})

    order_id_at_container = int_value(info.get("order_id"))
    cards = info.get("order_list_cards")
    if not isinstance(cards, list):
        return []

    matches: list[OrderMatch] = []
    for card in cards:
        if not isinstance(card, dict):
            continue

        # CRITICAL: for checkout_list_detail the actual Order ID is inside the
        # order card. info.order_id is absent in the newly-created state.
        order_id = int_value(card.get("order_id")) or order_id_at_container

        shop = card.get("shop_info")
        if not isinstance(shop, dict):
            shop = {}
        item = nested_first_item(card) or {}

        product_name = text_field(item, "name")
        variation = text_field(item, "model_name")
        item_id = int_value(item.get("item_id"))
        model_id = int_value(item.get("model_id"))
        shop_id = int_value(shop.get("shop_id")) or int_value(item.get("shop_id"))

        match = OrderMatch(
            source_url=source_url,
            container_index=index,
            container_type=container_type,
            checkout_id=checkout_id,
            order_id=order_id,
            status=status_label or status_text,
            status_label=status_label,
            payment_method=payment_method,
            payment_deadline=deadline,
            payment_deadline_raw=raw_deadline,
            shop_id=shop_id,
            shop_name=text_field(shop, "shop_name"),
            seller_username=text_field(shop, "username"),
            item_id=item_id,
            model_id=model_id,
            product_name=product_name,
            variation=variation,
            quantity=int_value(item.get("amount")),
            item_price=int_value(item.get("item_price")),
            original_price=int_value(item.get("price_before_discount")),
            order_price=int_value(item.get("order_price")),
            subtotal=int_value(info.get("subtotal")),
            final_total=int_value(info.get("final_total")),
            checkout_status=checkout_status,
            raw_card=card,
        )
        matches.append(match)

    return matches


def target_matches(match: OrderMatch, target: Target) -> tuple[bool, list[str]]:
    failures: list[str] = []

    if target.checkout_id is not None and match.checkout_id != target.checkout_id:
        failures.append(f"checkout_id {match.checkout_id} != {target.checkout_id}")

    if target.item_id is not None and match.item_id != target.item_id:
        failures.append(f"item_id {match.item_id} != {target.item_id}")

    if target.model_id is not None and match.model_id != target.model_id:
        failures.append(f"model_id {match.model_id} != {target.model_id}")

    if target.shop_id is not None and match.shop_id != target.shop_id:
        failures.append(f"shop_id {match.shop_id} != {target.shop_id}")

    if target.product_name:
        expected = normalize(target.product_name).lower()
        actual = normalize(match.product_name or "").lower()
        if expected not in actual and actual not in expected:
            failures.append("product name does not match")

    return not failures, failures


def print_match(match: OrderMatch) -> None:
    print_header("MATCHED ORDER")
    print(f"Shop             : {match.shop_name or '<not found>'}")
    print(f"Seller username  : {match.seller_username or '<not found>'}")
    print(f"Product          : {match.product_name or '<not found>'}")
    print(f"Variation        : {match.variation or '<not found>'}")
    print(f"Quantity         : {match.quantity if match.quantity is not None else '<not found>'}")
    print()
    print(f"Checkout ID      : {match.checkout_id if match.checkout_id is not None else '<not found>'}")
    print(f"Order ID         : {match.order_id if match.order_id is not None else '<not found>'}")
    print()
    print(f"Item Price       : {money_php(match.item_price)}")
    print(f"Original Price   : {money_php(match.original_price)}")
    print(f"Order Price      : {money_php(match.order_price)}")
    print(f"Subtotal         : {money_php(match.subtotal)}")
    print(f"Order Total      : {money_php(match.final_total if match.final_total is not None else match.subtotal)}")
    print()
    print(f"Status           : {match.status or '<not found>'}")
    print(f"Payment Method   : {match.payment_method or '<not found>'}")
    if match.payment_deadline:
        print(f"Payment Deadline : {match.payment_deadline.strftime('%Y-%m-%d %I:%M:%S %p %Z')}")
    else:
        print("Payment Deadline : <not found>")
    print(f"Payment Raw      : {match.payment_deadline_raw!r}")
    print(f"Source API       : {safe_url(match.source_url)}")
    print(f"Container        : {match.container_type}[{match.container_index}]")


def discord_payload_candidate(match: OrderMatch) -> dict[str, Any]:
    """Build a local, non-sending candidate for the future Discord notifier."""
    return {
        "event": "order_created",
        "status": match.status,
        "order_id": match.order_id,
        "checkout_id": match.checkout_id,
        "shop": match.shop_name,
        "seller": match.seller_username,
        "product": match.product_name,
        "variation": match.variation,
        "quantity": match.quantity,
        "item_price_php": round((match.item_price or 0) / 100000, 2) if match.item_price is not None else None,
        "original_price_php": round((match.original_price or 0) / 100000, 2) if match.original_price is not None else None,
        "order_total_php": round(((match.final_total if match.final_total is not None else match.subtotal) or 0) / 100000, 2)
        if (match.final_total is not None or match.subtotal is not None)
        else None,
        "payment_method": match.payment_method,
        "payment_deadline": match.payment_deadline.isoformat() if match.payment_deadline else None,
    }


def print_header(title: str) -> None:
    print("\n" + "=" * 78)
    print(title)
    print("=" * 78)


def collect_candidate_fields(value: Any, path: str = "$", depth: int = 0) -> list[tuple[str, Any]]:
    if depth > MAX_JSON_DEPTH:
        return []
    found: list[tuple[str, Any]] = []
    if isinstance(value, dict):
        for key, child in list(value.items())[:MAX_JSON_ITEMS]:
            key_text = str(key)
            child_path = f"{path}.{key_text}"
            if not key_is_sensitive(key_text) and any(
                marker in key_text.lower()
                for marker in ("order", "checkout", "item", "model", "shop", "price", "total", "payment", "deadline", "status")
            ):
                found.append((child_path, child))
            found.extend(collect_candidate_fields(child, child_path, depth + 1))
    elif isinstance(value, list):
        for index, child in enumerate(value[:MAX_JSON_ITEMS]):
            found.extend(collect_candidate_fields(child, f"{path}[{index}]", depth + 1))
    return found


async def inspect_purchase_page(page: Any, target: Target, wait_seconds: float) -> None:
    observed_responses: list[dict[str, Any]] = []

    async def on_response(response: Any) -> None:
        url = response.url
        lowered = url.lower()
        if ORDER_LIST_ENDPOINT not in lowered:
            return
        if response.status != 200:
            return
        record: dict[str, Any] = {
            "method": getattr(response.request, "method", "GET").upper(),
            "status": response.status,
            "url": url,
            "safe_url": safe_url(url),
            "content_type": "",
            "json": None,
            "json_error": None,
        }
        try:
            record["content_type"] = response.headers.get("content-type", "")
        except Exception:
            pass
        try:
            record["json"] = await response.json()
        except Exception as exc:
            record["json_error"] = str(exc)
        observed_responses.append(record)

    page.on("response", on_response)

    try:
        print_header("SHOPEE PURCHASE ORDER MATCH TEST")
        print(f"Target URL: {PURCHASE_URL}")
        print("Mode      : READ-ONLY / DISCOVERY")
        print("Actions   : NO purchase/payment/cancellation actions")
        print()
        print("TARGET FINGERPRINT")
        print(f"  Product : {target.product_name or '<any>'}")
        print(f"  Item ID : {target.item_id if target.item_id is not None else '<any>'}")
        print(f"  Model ID: {target.model_id if target.model_id is not None else '<any>'}")
        print(f"  Shop ID : {target.shop_id if target.shop_id is not None else '<any>'}")
        print(f"  Checkout: {target.checkout_id if target.checkout_id is not None else '<any>'}")

        print("\n[NAVIGATION] Opening /user/purchase/ in a separate browser tab...")
        await page.goto(PURCHASE_URL, wait_until="domcontentloaded", timeout=30000)
        try:
            await page.wait_for_load_state("networkidle", timeout=10000)
        except Exception:
            pass
        await asyncio.sleep(wait_seconds)

        print_header("PAGE STATE")
        print(f"URL   : {safe_url(page.url)}")
        try:
            print(f"Title : {normalize(await page.title())}")
        except Exception:
            print("Title : <unavailable>")

        body_text = ""
        try:
            body_text = normalize(await page.locator("body").inner_text(timeout=5000))
        except Exception as exc:
            print(f"Body  : <unavailable: {exc}>")
        if body_text:
            print("\nVISIBLE PAGE TEXT")
            print("-" * 78)
            print(body_text[:MAX_BODY_TEXT])
            if len(body_text) > MAX_BODY_TEXT:
                print("... <body text truncated>")

        # The response listener normally captures this request. If Shopee
        # served the page from an already-warmed connection before the listener
        # was attached, DOM inspection below still provides a fallback signal.
        print_header("AUTHORITATIVE ORDER LIST RESPONSE")
        print(f"Matching responses observed: {len(observed_responses)}")

        all_matches: list[OrderMatch] = []
        for response in observed_responses:
            payload = response.get("json")
            for index, container_type, container in iter_order_containers(payload):
                all_matches.extend(
                    build_match(
                        payload,
                        response["url"],
                        index,
                        container_type,
                        container,
                    )
                )

        # De-duplicate repeated responses/cards without hiding the actual
        # checkout-vs-order distinction.
        unique: dict[tuple[Any, ...], OrderMatch] = {}
        for match in all_matches:
            key = (
                match.checkout_id,
                match.order_id,
                match.item_id,
                match.model_id,
                match.shop_id,
                match.product_name,
            )
            unique[key] = match
        all_matches = list(unique.values())

        print(f"Parsed order cards: {len(all_matches)}")
        for index, match in enumerate(all_matches, start=1):
            print(
                f"  [{index}] order_id={match.order_id!r} checkout_id={match.checkout_id!r} "
                f"item_id={match.item_id!r} model_id={match.model_id!r} "
                f"shop_id={match.shop_id!r} status={match.status!r} "
                f"product={normalize(match.product_name or '')[:100]!r}"
            )

        print_header("TARGET MATCHING")
        matched: list[OrderMatch] = []
        for match in all_matches:
            ok, _ = target_matches(match, target)
            if ok:
                matched.append(match)

        if len(matched) == 1:
            print("MATCH STATUS: UNIQUE MATCH FOUND")
            print_match(matched[0])

            if matched[0].order_id is None:
                raise RuntimeError(
                    "Matched checkout has no actual Order ID in order_list_cards[*].order_id."
                )

            print_header("DISCORD PAYLOAD CANDIDATE — NOT SENT")
            print(json.dumps(discord_payload_candidate(matched[0]), ensure_ascii=False, indent=2))

        elif len(matched) > 1:
            print(f"MATCH STATUS: AMBIGUOUS — {len(matched)} matching cards found")
            for match in matched:
                print_match(match)
            raise RuntimeError(
                "More than one order card matched the supplied monitored-item fingerprint. "
                "Add --checkout-id, --item-id, --model-id, or --shop-id to disambiguate."
            )

        else:
            print("MATCH STATUS: NO MATCH FOUND")
            print("\nAvailable order cards were listed above.")
            print("This test will NOT click anything to create or modify an order.")
            raise RuntimeError(
                "The monitored-item fingerprint was not found on /user/purchase/."
            )

        print_header("INSPECTION COMPLETE")
        print("Read-only order discovery succeeded.")
        print("No purchase, payment, cancellation, or write action was performed.")
        print("No Discord request was sent.")

    finally:
        try:
            page.remove_listener("response", on_response)
        except Exception:
            pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Read-only Shopee /user/purchase/ order matching test."
    )
    parser.add_argument("--product-name", help="Exact or partial product name to match")
    parser.add_argument("--item-id", type=int, help="Shopee item_id to match")
    parser.add_argument("--model-id", type=int, help="Shopee model_id to match")
    parser.add_argument("--shop-id", type=int, help="Shopee shop_id to match")
    parser.add_argument("--checkout-id", type=int, help="Checkout ID to match")
    parser.add_argument(
        "--wait-seconds",
        type=float,
        default=3.0,
        help="Extra read-only wait after navigation (default: 3 seconds)",
    )
    return parser.parse_args()


def build_target(args: argparse.Namespace) -> Target:
    # If the caller supplied any selector, do not silently mix it with the
    # known successful item's identifiers. This makes alternate tests precise.
    supplied = any(
        value is not None
        for value in (
            args.product_name,
            args.item_id,
            args.model_id,
            args.shop_id,
            args.checkout_id,
        )
    )
    if supplied:
        return Target(
            product_name=args.product_name,
            item_id=args.item_id,
            model_id=args.model_id,
            shop_id=args.shop_id,
            checkout_id=args.checkout_id,
        )

    return Target(
        product_name=DEFAULT_PRODUCT_NAME,
        item_id=DEFAULT_ITEM_ID,
        model_id=DEFAULT_MODEL_ID,
        shop_id=DEFAULT_SHOP_ID,
    )


def main() -> None:
    args = parse_args()
    target = build_target(args)

    runtime = AsyncRuntime.instance()
    engine = BrowserEngine.instance()
    owner = object()

    future = runtime.submit(engine.open_session(owner, "about:blank"))
    session = future.result(timeout=30)
    page = session.page

    try:
        runtime.submit(
            inspect_purchase_page(page, target, max(0.0, args.wait_seconds))
        ).result(timeout=120)
    finally:
        runtime.submit(engine.close_session(owner)).result(timeout=15)


if __name__ == "__main__":
    main()
