from playwright.sync_api import sync_playwright
from pathlib import Path
from datetime import datetime
import json

# ============================================================
# CONFIG
# ============================================================

CART_URL = "https://shopee.ph/cart"

timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

RUN_DIR = Path("api_logs") / f"cart_{timestamp}"
RESPONSES_DIR = RUN_DIR / "responses"

RESPONSES_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# HELPERS
# ============================================================

saved = set()


def save_response(response):
    """
    Save interesting JSON/API responses generated by the cart page.
    """

    url = response.url

    # Only inspect API-looking requests.
    if "/api/" not in url:
        return

    try:
        content_type = response.headers.get("content-type", "")
    except Exception:
        return

    if "application/json" not in content_type:
        return

    # Avoid saving the exact same URL repeatedly.
    key = (
        response.request.method,
        url,
    )

    if key in saved:
        return

    saved.add(key)

    try:
        data = response.json()
    except Exception:
        return

    # Create a safe filename.
    endpoint = url.split("?")[0].rstrip("/").split("/")[-1]

    if not endpoint:
        endpoint = "api_response"

    filename = endpoint

    # Prevent filename collisions.
    counter = 1
    output = RESPONSES_DIR / f"{filename}.json"

    while output.exists():
        output = RESPONSES_DIR / f"{filename}_{counter}.json"
        counter += 1

    with open(output, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Saved: {output}")


# ============================================================
# MAIN
# ============================================================

with sync_playwright() as p:

    # Connect to the already-running Chrome.
    browser = p.chromium.connect_over_cdp(
        "http://127.0.0.1:9222"
    )

    print("Connected to Chrome.")

    # Use the existing logged-in Chrome context.
    context = browser.contexts[0]

    # Create a dedicated investigation tab.
    page = context.new_page()

    # Capture responses before navigation begins.
    page.on("response", save_response)

    print("Opening Shopee cart...")

    page.goto(
        CART_URL,
        wait_until="domcontentloaded",
        timeout=60000
    )

    print("Cart page loaded.")

    # Give Shopee's JavaScript/API requests time to finish.
    page.wait_for_timeout(10000)

    print()
    print("============================================================")
    print("CART API CAPTURE COMPLETE")
    print("============================================================")
    print(f"Saved responses to:")
    print(RESPONSES_DIR.resolve())
    print()
    print(f"Captured API responses: {len(saved)}")
    print()
    print("Press ENTER to close...")

    input()

    page.close()